import React from 'react';
import styles from "./CardInformation.module.css";
import Img from "../../img/3.png";
import Chip from "../Chip";

const abilities = [
   {
      "ability":{
         "name":"blaze",
         "url":"https://pokeapi.co/api/v2/ability/66/"
      },
      "is_hidden":false,
      "slot":1
   },
   {
      "ability":{
         "name":"solar-power",
         "url":"https://pokeapi.co/api/v2/ability/94/"
      },
      "is_hidden":true,
      "slot":3
   }
];

const moves = [
   {
      "move":{
         "name":"mega-punch",
         "url":"https://pokeapi.co/api/v2/move/5/"
      },
      "version_group_details":[
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"red-blue",
               "url":"https://pokeapi.co/api/v2/version-group/1/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"yellow",
               "url":"https://pokeapi.co/api/v2/version-group/2/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"emerald",
               "url":"https://pokeapi.co/api/v2/version-group/6/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"firered-leafgreen",
               "url":"https://pokeapi.co/api/v2/version-group/7/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"sword-shield",
               "url":"https://pokeapi.co/api/v2/version-group/20/"
            }
         }
      ]
   },
   {
      "move":{
         "name":"fire-punch",
         "url":"https://pokeapi.co/api/v2/move/7/"
      },
      "version_group_details":[
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"gold-silver",
               "url":"https://pokeapi.co/api/v2/version-group/3/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"crystal",
               "url":"https://pokeapi.co/api/v2/version-group/4/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"emerald",
               "url":"https://pokeapi.co/api/v2/version-group/6/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"platinum",
               "url":"https://pokeapi.co/api/v2/version-group/9/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"heartgold-soulsilver",
               "url":"https://pokeapi.co/api/v2/version-group/10/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"black-2-white-2",
               "url":"https://pokeapi.co/api/v2/version-group/14/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"omega-ruby-alpha-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/16/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"ultra-sun-ultra-moon",
               "url":"https://pokeapi.co/api/v2/version-group/18/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"lets-go-pikachu-lets-go-eevee",
               "url":"https://pokeapi.co/api/v2/version-group/19/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"sword-shield",
               "url":"https://pokeapi.co/api/v2/version-group/20/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"scarlet-violet",
               "url":"https://pokeapi.co/api/v2/version-group/25/"
            }
         }
      ]
   },
   {
      "move":{
         "name":"thunder-punch",
         "url":"https://pokeapi.co/api/v2/move/9/"
      },
      "version_group_details":[
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"platinum",
               "url":"https://pokeapi.co/api/v2/version-group/9/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"heartgold-soulsilver",
               "url":"https://pokeapi.co/api/v2/version-group/10/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"black-2-white-2",
               "url":"https://pokeapi.co/api/v2/version-group/14/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"omega-ruby-alpha-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/16/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"ultra-sun-ultra-moon",
               "url":"https://pokeapi.co/api/v2/version-group/18/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"lets-go-pikachu-lets-go-eevee",
               "url":"https://pokeapi.co/api/v2/version-group/19/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"sword-shield",
               "url":"https://pokeapi.co/api/v2/version-group/20/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"scarlet-violet",
               "url":"https://pokeapi.co/api/v2/version-group/25/"
            }
         }
      ]
   },
   {
      "move":{
         "name":"scratch",
         "url":"https://pokeapi.co/api/v2/move/10/"
      },
      "version_group_details":[
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"red-blue",
               "url":"https://pokeapi.co/api/v2/version-group/1/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"yellow",
               "url":"https://pokeapi.co/api/v2/version-group/2/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"gold-silver",
               "url":"https://pokeapi.co/api/v2/version-group/3/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"crystal",
               "url":"https://pokeapi.co/api/v2/version-group/4/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"ruby-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/5/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"emerald",
               "url":"https://pokeapi.co/api/v2/version-group/6/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"firered-leafgreen",
               "url":"https://pokeapi.co/api/v2/version-group/7/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"diamond-pearl",
               "url":"https://pokeapi.co/api/v2/version-group/8/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"platinum",
               "url":"https://pokeapi.co/api/v2/version-group/9/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"heartgold-soulsilver",
               "url":"https://pokeapi.co/api/v2/version-group/10/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"black-white",
               "url":"https://pokeapi.co/api/v2/version-group/11/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"colosseum",
               "url":"https://pokeapi.co/api/v2/version-group/12/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"xd",
               "url":"https://pokeapi.co/api/v2/version-group/13/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"black-2-white-2",
               "url":"https://pokeapi.co/api/v2/version-group/14/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"x-y",
               "url":"https://pokeapi.co/api/v2/version-group/15/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"omega-ruby-alpha-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/16/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"sun-moon",
               "url":"https://pokeapi.co/api/v2/version-group/17/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"ultra-sun-ultra-moon",
               "url":"https://pokeapi.co/api/v2/version-group/18/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"lets-go-pikachu-lets-go-eevee",
               "url":"https://pokeapi.co/api/v2/version-group/19/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"sword-shield",
               "url":"https://pokeapi.co/api/v2/version-group/20/"
            }
         },
         {
            "level_learned_at":1,
            "move_learn_method":{
               "name":"level-up",
               "url":"https://pokeapi.co/api/v2/move-learn-method/1/"
            },
            "version_group":{
               "name":"scarlet-violet",
               "url":"https://pokeapi.co/api/v2/version-group/25/"
            }
         }
      ]
   },
   {
      "move":{
         "name":"swords-dance",
         "url":"https://pokeapi.co/api/v2/move/14/"
      },
      "version_group_details":[
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"red-blue",
               "url":"https://pokeapi.co/api/v2/version-group/1/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"yellow",
               "url":"https://pokeapi.co/api/v2/version-group/2/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"ruby-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/5/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"emerald",
               "url":"https://pokeapi.co/api/v2/version-group/6/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"emerald",
               "url":"https://pokeapi.co/api/v2/version-group/6/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"firered-leafgreen",
               "url":"https://pokeapi.co/api/v2/version-group/7/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"tutor",
               "url":"https://pokeapi.co/api/v2/move-learn-method/3/"
            },
            "version_group":{
               "name":"firered-leafgreen",
               "url":"https://pokeapi.co/api/v2/version-group/7/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"diamond-pearl",
               "url":"https://pokeapi.co/api/v2/version-group/8/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"diamond-pearl",
               "url":"https://pokeapi.co/api/v2/version-group/8/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"platinum",
               "url":"https://pokeapi.co/api/v2/version-group/9/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"platinum",
               "url":"https://pokeapi.co/api/v2/version-group/9/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"egg",
               "url":"https://pokeapi.co/api/v2/move-learn-method/2/"
            },
            "version_group":{
               "name":"heartgold-soulsilver",
               "url":"https://pokeapi.co/api/v2/version-group/10/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"heartgold-soulsilver",
               "url":"https://pokeapi.co/api/v2/version-group/10/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"black-white",
               "url":"https://pokeapi.co/api/v2/version-group/11/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"black-2-white-2",
               "url":"https://pokeapi.co/api/v2/version-group/14/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"x-y",
               "url":"https://pokeapi.co/api/v2/version-group/15/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"omega-ruby-alpha-sapphire",
               "url":"https://pokeapi.co/api/v2/version-group/16/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"sun-moon",
               "url":"https://pokeapi.co/api/v2/version-group/17/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"ultra-sun-ultra-moon",
               "url":"https://pokeapi.co/api/v2/version-group/18/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"sword-shield",
               "url":"https://pokeapi.co/api/v2/version-group/20/"
            }
         },
         {
            "level_learned_at":0,
            "move_learn_method":{
               "name":"machine",
               "url":"https://pokeapi.co/api/v2/move-learn-method/4/"
            },
            "version_group":{
               "name":"scarlet-violet",
               "url":"https://pokeapi.co/api/v2/version-group/25/"
            }
         }
      ]
   }
]

const CardInformation = () => {
   return (
      <div className={styles.container}>
         <div className={styles.bgBlue} />
         <div className={styles.bgImage}>
            <img src={Img} alt=""/>
         </div>
         <div className={styles.information}>
            <h2>Venusaur</h2>
            <div className={styles.informationDetailOne}>
               <div>
                  <h4>Height</h4>
                  <h5>{6/10} m</h5>
               </div>
               <div>
                  <h4>Weight</h4>
                  <h5>{85/10} kg</h5>
               </div>
            </div>
            <div className={styles.informationDetailTwo}>
               <h4>Abilities</h4>
               <Chip
                  data={abilities}
                  type="ability"
                  color="#151D3B"
               />
            </div>
            <div className={styles.informationDetailTwo}>
               <h4>Moves</h4>
               <Chip
                  data={moves}
                  type="move"
                  color="#D82148"
               />
            </div>
         </div>
      </div>
   );
};

export default CardInformation;
